// Weird Canada Player (c) 2013 Mike Verdone
// Unscrunched code at: http://github.com/sixohsix/weird-player/
(function() {
'use strict';window.weirdPlayer=window.weirdPlayer||{};
window.weirdPlayer.util=function(a){function e(f){return void 0!==f}var b={},l=a.console.log.bind(a.console);b.debug=!1;b.log=function(f){b.debug&&l(f)};b.defined=e;b.coerce=function(f,a){return e(f)?f:a};b.maybe=function(a,b,h){return e(a)?b(a):h};b.attr=function(a,b,h){return e(a)&&e(a[b])?a[b]:h};b.query=function(a,b){for(var e=a.querySelectorAll(b),g=[],c=0;c<e.length;c++)g.push(e[c]);return g};b.empty=function(a){return 0===a.length};b.append=function(a,b){b.forEach(function(b){a.push(b)})};
b.choose=function(a){return a[Math.random()*a.length|0]};return b}(window);
window.weirdPlayer.parse=function(a){function e(a,b){s("parseFail: "+a);return b}function b(a){return a.posts[0]}function l(a){a=a.content;var b=document.implementation.createHTMLDocument("jail").createElement("div");b.innerHTML=a;return b}function f(a){a=n(a,"audio").map(function(a){return n(a,"source")}).filter(function(a){return 0<a.length});return q(a)?e("no audio source nodes found",[]):a}function p(a){if(!r(a.title))return e("missing post title");var b=m.exec(a.title);return null===b?e("title match failed: "+
a.title):{artist:b[1],release:b[2]}}function h(a){return n(a,"p.audioTrack a").map(function(a){a=t.exec(a.innerHTML);return null===a?void 0:a[1]}).filter(r)}function g(a){a=a.querySelector("img");var b=document.createElement("img");null!==a&&(b.src=a.src);return b}var c={},d=a.RegExp;a=a.weirdPlayer.util;var r=a.defined,n=a.query,q=a.empty,s=a.log;c.singlePost=b;c.htmlContent=l;c.parseAudioNodes=f;var m=new d("^New Canadiana :: (.+) &#8211; (.+)$");c.parseArtistData=p;var t=new d("^.*\u2013 (.+)$");
c.parseSongTitleLinks=h;c.parseImage=g;c.parsePostUrl=function(a){return a.url};c.parse=function(a){var c=b(a);if(!r(c))return[];var n=l(c);a=p(c);var q=f(n),d=h(n),n=g(n),c=c.url;if(!(r(a)&&r(q)&&r(d)&&r(n)&&q.length===d.length))return[];for(var e=[],v=0;v<d.length;v++)e.push({artist:a.artist,release:a.release,image:n,sources:q[v],title:d[v],postUrl:c});return e};return c}(window);
window.weirdPlayer.loader=function(a){function e(a){var b="?json=get_recent_posts",c;for(c in a)b+="&"+c+"="+a[c];return b}function b(b,c,d,g){c=e(c);var m=new a.XMLHttpRequest;g=g||h;m.onload=d.bind(void 0,m);m.onerror=g.bind(void 0,m);m.open("GET",b+c);m.send()}function l(b,c,g){var s="pureEvil"+d,m=document.createElement("script"),f=document.querySelector("head");d++;a[s]=function(b){f.removeChild(m);delete a[s];g(b)};c.callback=s;m.src=b+e(c);f.appendChild(m)}var f={},p=a.weirdPlayer.util,h=p.doNothing,
g=p.attr,c=a.weirdPlayer.parse.parse,d=0;f.createLoader=function(d){function e(c,d){b(f,c,function(b){b="json"===b.responseType?b.response:a.JSON.parse(b.responseText);d(b)},function(a){d({})})}var q={},f=g(d,"apiUrl","/category/content/newcanadiana/"),m=g(d,"pages",905),h=g(d,"jsonp",!1);q.loadSongs=function(a){function b(d){m=g(d,"pages",m);a(c(d))}var d={count:"1",page:""+(Math.random()*m|0)};h?l(f,d,b):e(d,b)};return q};f.createTestLoader=function(b){var d={},g=0;d.loadSongs=function(d){var e=
c(b[g]);g=(g+1)%b.length;a.setTimeout(d.bind(void 0,e),0)};return d};return f}(window);
window.weirdPlayer.actions=function(a){var e={},b=a.weirdPlayer.util,l=b.coerce,f=b.append,p=b.empty,h=b.log;e.createActionChain=function(){function b(){if(!p(c)){var d=c.pop();h("action: "+d.name);a.setTimeout(d,0)}}var c=[],d={doActions:function(a){f(c,a.reverse());b()}};d.doneAction=b;d.asAction=function(a){return function(){a.apply(void 0,arguments);b()}};return d};e.doNothing=function(){};e.createEventCoordinator=function(){var a={},b={};a.observe=function(d,e){b[d]=l(a[d],[]);b[d].push(e)};
a.notify=function(a){l(b[a],[]).forEach(function(a){a()})};return a};return e}(window);
window.weirdPlayer.translate=function(a){function e(a,b,c){var e=p(a,c,{});f(b,".tr").forEach(function(a){var b=a.tr_origHTML=p(a,"tr_origHTML",a.innerHTML);g(e[b])||h("missing "+c+" translation for '"+b+"'");a.innerHTML=p(e,b,b)})}var b={},l=a.weirdPlayer.util,f=l.query,p=l.attr,h=l.log,g=l.defined;b.translations={fr:{"Now playing:":"Joue maintenant:","Play/Pause":"Commence/Pause","Next&nbsp;song":"Prochaine&nbsp;chanson","Visit Weird Canada":"Visitez Weird-Canada"},de:{"Now playing:":"Jetzt spielt:",
"Play/Pause":"Spiel/Halt","Next&nbsp;song":"N\u00e4chste&nbsp;Lied","Visit Weird Canada":"Checken Sie Weird-Canada aus"}};b.translate=e;b.createTranslator=function(a,b){var c={},g="en";c.setLang=function(c){c!==g&&(g=c,e(a,b,c))};return c};var c=new a.RegExp("(..)-..");b.getBrowserLanguage=function(){var b=a.navigator.userLanguage||a.navigator.language,e=c.exec(b);null!==e&&(b=e[1]);return b};return b}(window);
window.weirdPlayer.main=function(a){function e(a){function b(){a.loadSongs(function(a){d(a)||(a=n?a:[s(a)],r(l,a));f.doneAction()})}function c(){function a(){l.length===d?f.doActions([b,a]):(m.notify("gotNewSongs"),f.doneAction())}var d=l.length;f.doActions([a])}function e(){d(l)?f.doActions([c,e]):(h=l.shift(),m.notify("songChanged"),d(l)?f.doActions([c]):f.doneAction())}var g={},f=t.createActionChain(),m=t.createEventCoordinator(),h=void 0,n=!0,l=[];g.skip=function(){f.doActions([e])};g.getCurrentSong=
function(){return h};g.observe=m.observe;return g}function b(a,b){function d(b,e){c(a,b).forEach(function(a){a.innerHTML=e})}d(".wcp-artist",b.artist);d(".wcp-title",b.title);d(".wcp-release",b.release);c(a,".wcp-postUrl").forEach(function(a){a.href=b.postUrl});c(a,".wcp-img").forEach(function(a){a.innerHTML="";a.appendChild(b.image)})}function l(a){var b=document.createElement("audio");a.forEach(function(a){b.appendChild(a)});b.load();return b}function f(a){var b=a%60|0;10>b&&(b="0"+b);return""+
(a/60|0)+":"+b}function p(d,e,g){function h(){var a=q(k,"duration",0)|0,b=q(k,"currentTime",0)|0,c=q(k,"ended",!1);s.forEach(function(c){c.max=a;c.value=b});t.forEach(function(a){a.innerHTML=f(b)});u.forEach(function(b){b.innerHTML=f(a)});c&&!r&&(p=r=!0,d.skip())}var k,p=n(g)?g:!1,r=!1,s=c(e,".wcp-progress"),t=c(e,".wcp-curTime"),u=c(e,".wcp-totTime");d.observe("songChanged",function(){m("song changed, yo");var a=d.getCurrentSong(),c=a.sources;n(k)&&(k.pause(),e.removeChild(k));k=l(c);e.appendChild(k);
p&&(p=!1,k.play());r=!1;b(e,a);h()});c(e,".wcp-play").forEach(function(a){a.onclick=function(){n(k)&&k.paused&&k.play();return!1}});c(e,".wcp-pause").forEach(function(a){a.onclick=function(){n(k)&&!k.paused&&k.pause();return!1}});c(e,".wcp-skip").forEach(function(a){a.onclick=function(){n(k)&&k.pause();p=!0;d.skip();return!1}});c(e,".wcp-playPause").forEach(function(a){a.onclick=function(){n(k)&&(k.paused?k.play():k.pause());return!1}});d.skip();a.setInterval(h,1E3)}var h={},g=a.weirdPlayer.util,
c=g.query,d=g.empty,r=g.append,n=g.defined,q=g.attr,s=g.choose,m=g.log,t=a.weirdPlayer.actions,w=a.weirdPlayer.loader.createLoader,x=a.weirdPlayer.loader.createTestLoader,u=a.weirdPlayer.translate,y=u.createTranslator,z=u.translations,A=u.getBrowserLanguage;h.setup=function(b,d){var f=q(d,"debug",!1),l=q(d,"useTestLoader",!1),k=q(d,"autoplay",!1);g.debug=f;var f=l?x(a.tests.fixture.responses):w({apiUrl:d.apiUrl,jsonp:d.jsonp}),f=e(f),k=p(f,b,k),h=y(z,document);h.setLang(A());["en","fr"].forEach(function(a){c(document,
".setLang-"+a).forEach(function(b){b.onclick=function(){h.setLang(a);return!1}})});b.wcpModel=f;b.wcpView=k;b.wcpTranslator=h;return k};return h}(window);

})();
