// Weird Canada Player (c) 2013 Mike Verdone
// Unscrunched code at: http://github.com/sixohsix/weird-player/
(function() {
'use strict';window.weirdPlayer=window.weirdPlayer||{};
window.weirdPlayer.util=function(c){function d(e){return void 0!==e}var b={},h=c.console.log.bind(c.console);b.debug=!1;b.log=function(e){b.debug&&h(e)};b.defined=d;b.coerce=function(e,c){return d(e)?e:c};b.maybe=function(e,c,b){return d(e)?c(e):b};b.attr=function(e,c,b){return d(e)?e[c]:b};b.query=function(c,b){for(var d=c.querySelectorAll(b),l=[],a=0;a<d.length;a++)l.push(d[a]);return l};b.empty=function(c){return 0===c.length};b.append=function(c,b){b.forEach(function(b){c.push(b)})};b.choose=
function(c){return c[Math.random()*c.length|0]};return b}(window);
window.weirdPlayer.parse=function(c){function d(a,r){u("parseFail: "+a);return r}function b(a){return a.posts[0]}function h(a){a=a.content;var r=document.createElement("div");r.innerHTML=a;return r}function e(a){a=f(a,"audio").map(function(a){return f(a,"source")}).filter(function(a){return 0<a.length});return t(a)?d("no audio source nodes found",[]):a}function p(a){if(!g(a.title))return d("missing post title");var r=s.exec(a.title);return null===r?d("title match failed: "+a.title):{artist:r[1],release:r[2]}}
function q(a){return f(a,"p.audioTrack a").map(function(a){a=v.exec(a.innerHTML);return null===a?void 0:a[1]}).filter(g)}function l(a){a=a.querySelector("img");var c=document.createElement("img");null!==a&&(c.src=a.src);return c}var a={},m=c.RegExp;c=c.weirdPlayer.util;var g=c.defined,f=c.query,t=c.empty,u=c.log;a.singlePost=b;a.htmlContent=h;a.parseAudioNodes=e;var s=new m("^New Canadiana :: (.+) &#8211; (.+)$");a.parseArtistData=p;var v=new m("^.*\u2013 (.+)$");a.parseSongTitleLinks=q;a.parseImage=
l;a.parsePostUrl=function(a){return a.url};a.parse=function(a){var c=b(a);if(!g(c))return[];var n=h(c);a=p(c);var f=e(n),k=q(n),n=l(n),c=c.url;if(!(g(a)&&g(f)&&g(k)&&g(n)&&f.length===k.length))return[];for(var m=[],d=0;d<k.length;d++)m.push({artist:a.artist,release:a.release,image:n,sources:f[d],title:k[d],postUrl:c});return m};return a}(window);
window.weirdPlayer.loader=function(c){function d(b,a,m,g){var f="?json=get_recent_posts",d;for(d in a)f+="&"+d+"="+a[d];a=f;f=new c.XMLHttpRequest;g=g||e;f.onload=m.bind(void 0,f);f.onerror=g.bind(void 0,f);f.open("GET",b+a);f.send()}var b={},h=c.weirdPlayer.util,e=h.doNothing,p=h.attr,q=c.weirdPlayer.parse.parse;b.createLoader=function(b){var a={},m=p(b,"apiUrl","/category/content/newcanadiana/"),g=p(b,"pages",905);a.loadSongs=function(a){var b={count:"1",page:""+(Math.random()*g|0)};d(m,b,function(b){b=
"json"===b.responseType?b.response:c.JSON.parse(b.responseText);g=p(b,"pages",g);a(q(b))},function(c){a([])})};return a};b.createTestLoader=function(b){var a={},d=0;a.loadSongs=function(a){var f=q(b[d]);d=(d+1)%b.length;c.setTimeout(a.bind(void 0,f),0)};return a};return b}(window);
window.weirdPlayer.actions=function(c){var d={},b=c.weirdPlayer.util,h=b.coerce,e=b.append,p=b.empty,q=b.log;d.createActionChain=function(){function b(){if(!p(a)){var d=a.pop();q("action: "+d.name);c.setTimeout(d,0)}}var a=[],d={doActions:function(c){e(a,c.reverse());b()}};d.doneAction=b;d.asAction=function(a){return function(){a.apply(void 0,arguments);b()}};return d};d.doNothing=function(){};d.createEventCoordinator=function(){var b={},a={};b.observe=function(c,d){a[c]=h(b[c],[]);a[c].push(d)};
b.notify=function(b){h(a[b],[]).forEach(function(a){a()})};return b};return d}(window);
window.weirdPlayer.main=function(c){function d(a){function b(){a.loadSongs(function(a){m(a)||h.push(t(a));e.doneAction()})}function c(){function a(){h.length===d?e.doActions([b,a]):(g.notify("gotNewSongs"),e.doneAction())}var d=h.length;e.doActions([a])}function d(){m(h)?e.doActions([c,d]):(l=h.shift(),g.notify("songChanged"),m(h)?e.doActions([c]):e.doneAction())}var f={},e=s.createActionChain(),g=s.createEventCoordinator(),l=void 0,h=[];f.skip=function(){e.doActions([d])};f.getCurrentSong=function(){return l};
f.observe=g.observe;return f}function b(b,c){function d(c,e){a(b,c).forEach(function(a){a.innerHTML=e})}d(".wcp-artist",c.artist);d(".wcp-title",c.title);d(".wcp-release",c.release);a(b,".wcp-postUrl").forEach(function(a){a.href=c.postUrl});a(b,".wcp-img").forEach(function(b){a(b,"img").forEach(function(a){b.removeChild(a)});b.appendChild(c.image)})}function h(a){var b=document.createElement("audio");a.forEach(function(a){b.appendChild(a)});b.load();return b}function e(a){var b=a%60|0;10>b&&(b="0"+
b);return""+(a/60|0)+":"+b}function p(d,n){function l(){var a=f(k,"duration",0)|0,b=f(k,"currentTime",0)|0,c=f(k,"ended",!1);q.forEach(function(c){c.max=a;c.value=b});s.forEach(function(a){a.innerHTML=e(b)});t.forEach(function(b){b.innerHTML=e(a)});c&&!p&&(m=p=!0,d.skip())}var k,m=!1,p=!1,q=a(n,".wcp-progress"),s=a(n,".wcp-curTime"),t=a(n,".wcp-totTime");d.observe("songChanged",function(){u("song changed, yo");var a=d.getCurrentSong(),c=a.sources;g(k)&&(k.pause(),n.removeChild(k));k=h(c);n.appendChild(k);
m&&(m=!1,k.play());p=!1;b(n,a);l()});a(n,".wcp-play").forEach(function(a){a.onclick=function(){g(k)&&k.play();return!1}});a(n,".wcp-pause").forEach(function(a){a.onclick=function(){g(k)&&k.pause();return!1}});a(n,".wcp-skip").forEach(function(a){a.onclick=function(){g(k)&&k.pause();m=!0;d.skip();return!1}});n.wcpModel=d;d.skip();c.setInterval(l,500)}var q={},l=c.weirdPlayer.util,a=l.query,m=l.empty,g=l.defined,f=l.attr,t=l.choose,u=l.log,s=c.weirdPlayer.actions,v=c.weirdPlayer.loader.createLoader,
w=c.weirdPlayer.loader.createTestLoader;q.setup=function(a,b){var e=b.apiUrl,g=f(b,"debug",!1),h=f(b,"useTestLoader",!1);l.debug=g;e=h?w(c.tests.fixture.responses):v(e);e=d(e);return p(e,a)};return q}(window);

})();
